name: Auto-review pipeline

on:
    workflow_call:
    pull_request:
      branches: [ "master" ]

jobs:
  auto-review:
    env:
      GPT_TOKEN: ${{ secrets.GPT_TOKEN }}
    permissions:
      pull-requests: write 
    uses: xAdRx/auto-reviewer/.github/workflows/review.yml@test
